#!/bin/bash
# shell script to prepend i3status with more stuff

function memory_usage() {
    MEM_USAGE=$(awk '/MemTotal/ {memtotal=$2}; /MemAvailable/ {memavail=$2}; END { printf("%.0f", (100- (memavail / memtotal * 100))) }' /proc/meminfo)
}

function spotify_song() {
  dir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
  spotify_status=$(dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'PlaybackStatus' | tail -n1 | cut -d'"' -f2)
  spotify_artist=$(dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata' | awk -f ${dir}/spotify_song.awk | head -n 1 | cut -d':' -f2)
  spotify_song=$(dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata' | awk -f ${dir}/spotify_song.awk | tail -n 1 | cut -d':' -f2)
}


i3status $* | while :
do
    read line

    spotify_song
    memory_usage

    line=" ${MEM_USAGE}% | $line"

    if [ "$spotify_status" = "Playing" ] ; then
        echo -n " $spotify_artist - $spotify_song | $line" || exit 1
    else
        echo -n $line || exit 1
    fi
done
