#!/bin/sh
# shell script to prepend i3status with more stuff


i3status $* | while :
do
    read line
    MEM_USAGE=$(awk '/MemTotal/ {memtotal=$2}; /MemAvailable/ {memavail=$2}; END { printf("%.0f", (100- (memavail / memtotal * 100))) }' /proc/meminfo)
    echo "Mem ${MEM_USAGE}% | $line" || exit 1
done
