#!/usr/bin/env bash

# copy selected password to clipboard
if [[ -z $@ ]]; then
    prefix=${PASSWORD_STORE_DIR-~/.password-store}
    password_files=( "$prefix"/**/*.gpg )
    password_files=( "${password_files[@]#"$prefix"/}" )
    password_files=( "${password_files[@]%.gpg}" )

    printf '%s\n' "${password_files[@]}"
else
    if [ $# -ge 2 ] && [ "$1" == "--type" ]; then
        shift
        pass show "$*" | { IFS= read -r pass; printf %s "$pass"; } | xdotool type --clearmodifiers --file -
    else
        coproc $0 --type "$@"
    fi
fi 
