#! /bin/sh

wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

$HOME/.config/bspwm/autostart.sh

bspc config normal_border_color "#2e3440"
bspc config active_border_color "#2e3440"
bspc config focused_border_color "#d08770"
bspc config presel_feedback_color "#4c566a"

bspc config split_ratio 0.5
bspc config border_width 1
bspc config window_gap 7
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config single_monocle false

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus false
bspc config ignore_ewmh_focus false

bspc config remove_disabled_monitors false
bspc config remove_unplugged_monitors false
bspc monitor HDMI1 -d 5 6 7 8 9 10
bspc monitor HDMI2 -d 1 2 3 4
