#! /bin/sh

wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

$HOME/.config/bspwm/autostart.sh

bspc monitor HDMI1 -d 5 6 7 8 9 10 
bspc monitor HDMI2 -d 1 2 3 4

bspc config border_width         2
bspc config window_gap           5
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Dude state=floating center=or
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


# Color config
bspc config normal_border_color     "#2e3440"
bspc config focused_border_color    "#5e81ac"
bspc config active_border_color     "#2e3440"
bspc config presel_feedback_color   "#81a1c1"
