# aliases
alias rm 'rm -rfv'
alias ack 'ack-grep'
alias v 'vim'
alias py 'python'
alias taillog 'colortail -f -n0'
alias LESS '/usr/bin/less -MQRSi'
alias less '/usr/share/vim/vim74/macros/less.sh'
alias pi-stats 'ssh xbian@bzmediapi "echo -n"'
alias root 'sudo -i'
# git aliases
alias g 'git'
alias gsh 'git-sh'
alias st 'git st -s'
alias sl 'git sl'
alias log 'git log'
alias l 'git l'
alias co 'git co'
alias ci 'git ci'
alias br 'git br'
alias add 'git add'
alias d 'git d'
alias push 'git push'
alias pull 'git pull'
alias rb 'git rb'
alias rbi 'git rb'
alias rs 'git reset'
alias show 'git show'
alias stash 'git stash'
alias remote 'git remote'
alias clone 'git clone'
alias fetch 'git fetch'
alias bisect 'git bisect'
alias reflog 'git reflog'
alias merge 'git merge'
alias tag 'git tag'
# development aliases
alias tests './tests.fish'
alias build './build.fish'
alias check './check.fish'
alias clean './clean.fish'
alias run './run.fish'
alias gradlew './gradlew'
