# git aliases
alias g 'git'
alias st 'git st'
alias co 'git co'
alias ci 'git ci'
alias br 'git br'
alias d 'git d'
alias rb 'git rb'
alias rs 'git reset'
alias sl 'git sl'
alias log 'git l'
alias push 'git push'
alias pull 'git pull'
alias add 'git add'
alias show 'git show'
alias stash 'git stash'
alias remote 'git remote'
alias clone 'git clone'
alias fetch 'git f'
alias bisect 'git bisect'
alias reflog 'git reflog'
alias merge 'git merge'
alias tag 'git tag'
alias revert 'git revert'
