# git aliases
alias g 'git'
alias st 'git st -s'
alias sl 'git sl'
alias log 'git log'
alias l 'git l'
alias co 'git co'
alias ci 'git ci'
alias br 'git br'
alias add 'git add'
alias d 'git d'
alias push 'git push'
alias pull 'git pull'
alias rb 'git rb'
alias rbi 'git rbi'
alias rbc 'git rbc'
alias gwc 'git wc'
alias rs 'git reset'
alias show 'git show'
alias stash 'git stash'
alias remote 'git remote'
alias clone 'git clone'
alias fetch 'git fetch'
alias bisect 'git bisect'
alias reflog 'git reflog'
alias merge 'git merge'
alias tag 'git tag'
alias revert 'git revert'
