launcher:
  height: 400
  width: 1000
display:
  autoconfig_enabled: false
  wallpapers_dir: .config/wallpapers/
  screensaver_timeout_secs: 300
power:
  monitor_enabled: false  
polkit:
  agent: /usr/lib/x86_64-linux-gnu/polkit-mate/polkit-mate-authentication-agent-1
