# aliases
alias rm 'rm -rfv'
alias ack 'ack-grep'
alias v 'vim'
alias py 'python'
alias taillog 'colortail -f -n0'
alias LESS '/usr/bin/less -MQRSi'
alias less '/usr/share/vim/vim73/macros/less.sh'
# git aliases
alias g 'git'
alias gsh 'git-sh'
alias gg 'git gui'
alias st 'git st'
alias sl 'git sl'
alias log 'git log'
alias l 'git l'
alias co 'git co'
alias ci 'git ci'
alias br 'git br'
alias add 'git add'
alias d 'git d'
alias remote 'git remote'
alias clone 'git clone'
alias fetch 'git fetch'
