#! /bin/bash

SLEEP_TIME=5   
SAFE_PERCENT=30  
DANGER_PERCENT=25 
CRITICAL_PERCENT=10  
BATTERY='Battery 0'

while [ true ]; do

    if [[ -n $(acpi -b | grep -i discharging | grep "$BATTERY") ]]; then
        rem_bat=$(acpi -b | grep "$BATTERY" | grep -Eo "[0-9]+%" | grep -Eo "[0-9]+")

        if [[ $rem_bat -gt $SAFE_PERCENT ]]; then
            SLEEP_TIME=10
        else
            SLEEP_TIME=5
            if [[ $rem_bat -le $CRITICAL_PERCENT ]]; then
                SLEEP_TIME=1
                notify-send -t 1500 -u critical 'Battery Level Very Low'
            elif [[ $rem_bat -le $DANGER_PERCENT ]]; then
                sleep_time=2
                notify-send -t 1500 -u normal "Battery Level Below ${DANGER_PERCENT}%"
            fi

        fi
    else
        SLEEP_TIME=10
    fi

    sleep ${SLEEP_TIME}m
done
