#!/bin/bash

ping -c 1 8.8.8.8 > /dev/null
result=$?
echo -n "Conectivity test: "
if [ $result -eq 0 ]; then
    echo "OK"
else
    echo "FAIL"
fi

host ipredator.org > /dev/null
result=$?
echo -n "DNS test: "
if [ $result -eq 0 ]; then
    echo "OK"
else
    echo "FAIL"
    echo "Restarting dnscrypt-proxy"
    sudo systemctl restart dnscrypt-proxy 
fi

