#!/bin/bash 

function send_notification() {
    notify-send -t 1000 -u normal Light-Locker "$1"
}


LL=$(pgrep light-locker)
 
if [ $? == 0 ]; then
    kill $LL
    send_notification "Screensaver disabled"
else
    /usr/bin/light-locker &
    send_notification "Screensaver enabled"
fi

