#!/bin/bash
SINK=$(pactl info | awk '/^Default Sink:/ { print $3 }')
SOURCE=$(pactl info | awk '/^Default Source:/ { print $3 }')

function send_notification() {
    notify-send -t 1000 -u normal Volume "$1"
}

case $1 in
    up)
        pactl set-sink-volume "@DEFAULT_SINK@" +2%
        send_notification "Up +2%"
        ;;
    down)
        pactl set-sink-volume "@DEFAULT_SINK@" -2%
        send_notification "Down -2%"
        ;;
    mute)
        pactl set-sink-mute "@DEFAULT_SINK@" toggle
       send_notification "Output mute toggle"
        ;;
    mic)
        pactl set-source-mute "@DEFAULT_SOURCE@" toggle
        send_notification "Microfone mute toggle"
        ;;
    *)
        echo "Usage: $0 [up|down|mute|mic]"
        exit 1
        ;;
esac

