# Shell
shell /usr/bin/fish

# Font configuration
font_family      Source Code Pro
bold_font        Source Code Pro Bold
italic_font      Source Code Pro Italic
bold_italic_font Source Code Pro Bold Italic
font_size        14.0

# Theme: Nord
foreground            #D8DEE9
background            #2E3440
selection_foreground  #2E3440
selection_background  #D8DEE9
background_opacity    0.95

# Cursor
cursor                #81A1C1
cursor_text_color     #2E3440

# Color palette
# black
color0   #3B4252
color8   #4C566A
# red
color1   #BF616A
color9   #BF616A
# green
color2   #A3BE8C
color10  #A3BE8C
# yellow
color3   #EBCB8B
color11  #EBCB8B
# blue
color4   #81A1C1
color12  #81A1C1
# magenta
color5   #B48EAD
color13  #B48EAD
# cyan
color6   #88C0D0
color14  #8FBCBB
# white
color7   #E5E9F0
color15  #ECEFF4

# Mouse
copy_on_select yes

# Window Settings
window_alert_on_bell yes
remember_window_size  yes
window_padding_width 5
bell_on_tab "🔔 
hide_window_decorations no
linux_display_server x11
tab_title_template {session_name}:{name}
tab_bar_min_tabs 1

# Startup Session
startup_session ~/.config/kitty/sessions/home.kitty-session

# Keybindings
kitty_mod alt+shift
## new window
map kitty_mod+n new_window
## Move to window
map kitty_mod+up    neighboring_window up
map kitty_mod+down  neighboring_window down
map kitty_mod+left  neighboring_window left
map kitty_mod+right neighboring_window right
## Layout 
map kitty_mod+z toggle_layout stack
## Sessions
map alt+esc goto_session --active-only=no --sort-by=alphabetical ~/.config/kitty/sessions/

## Tab management
map ctrl+tab       next_tab
map ctrl+shift+tab previous_tab

# Scrollback settings
# Make the scroll back buffer absurdly large
scrollback_lines 100000
wheel_scroll_multiplier 5.0
touch_scroll_multiplier 5.0
scrollback_indicator_opacity 1.0

# Keyboard scrolling
map kitty_mod+page_up scroll_page_up
map kitty_mod+page_down scroll_page_down

## Kittens
map kitty_mod+a kitten agents.py
map kitty_mod+f kitten files.py
map kitty_mod+g kitten git.py
map kitty_mod+. kitten notes.py 
map kitty_mod+j kitten jrnl.py 

