# Shell
shell /usr/bin/fish

# Font configuration
font_family      Source Code Pro
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.0

# Mouse
copy_on_select yes

# Window Settings
window_alert_on_bell yes
remember_window_size  yes
window_padding_width 5
hide_window_decorations no
linux_display_server x11

# Scrollback settings
# Make the scroll back buffer absurdly large
scrollback_lines 100000
wheel_scroll_multiplier 5.0
touch_scroll_multiplier 5.0
scrollback_indicator_opacity 1.0

# Includes
include theme.conf
include tabs.conf
include maps.conf
