# Keybindings
kitty_mod alt+shift

## new window
map kitty_mod+n new_window

## Move to window
map kitty_mod+up    neighboring_window up
map kitty_mod+down  neighboring_window down
map kitty_mod+left  neighboring_window left
map kitty_mod+right neighboring_window right

## Layout 
map kitty_mod+z toggle_layout stack

## Sessions
map alt+esc goto_session --active-only=no --sort-by=alphabetical ~/.config/kitty/sessions/

## Tab management
map ctrl+tab       next_tab
map ctrl+shift+tab previous_tab

# Keyboard scrolling
map kitty_mod+page_up scroll_page_up
map kitty_mod+page_down scroll_page_down

## Kittens
map kitty_mod+a kitten agents.py
map kitty_mod+f kitten files.py
map kitty_mod+g kitten git.py
map kitty_mod+. kitten notes.py 
map kitty_mod+j kitten jrnl.py 
map kitty_mod+o kitten open_project.py 
