#! /bin/sh

wmname LG3D
pgrep -x sxhkd > /dev/null || sxhkd -c .config/bspwm/sxhkdrc &
pgrep -x polybar > /dev/null || polybar -c .config/bspwm/polybar main &
pgrep --full -x "dude session" > /dev/null || dude session &
pgrep -x dunst > /dev/null || dunst -config /home/dq/.config/bspwm/dunstrc

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Dude state=floating center=or
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


# Color config
bspc config normal_border_color     "#2e3440"
bspc config focused_border_color    "#4c566a"
bspc config active_border_color     "#2e3440"
bspc config presel_feedback_color   "#81a1c1"
